# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unn Swanström - UX Designer & Speaker
email: unnswanstrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UX designer and meetup organizer who likes tech and horses.
  A talkative Swedish vagabond currently based in Stockholm.
  IT Woman of the Year 2015.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unnderbar.com" # the base hostname & protocol for your site
twitter_username: unnderbar
github_username:  unnderbar

# Build settings
markdown: kramdown
permalink: pretty

gems:
 - jekyll-redirect-from
